name: lxg_au
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo.png
    - assets/logo1.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
